Vagrant.configure(2) do |config|
	# Ubuntu 14.04
	config.vm.box = "ubuntu/trusty64"
	config.vm.synced_folder "../project/", "/home/vagrant/project", :mount_options => ["dmode=777", "fmode=777"]

	# WebServer
	config.vm.define "web" do |web|
		web.vm.hostname = "web"
		web.vm.network "private_network", ip: "10.11.1.100", virtualbox__intnet: true

		web.vm.provider "virtualbox" do |v| 
			v.memory = 1024 
		end 

		web.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
		web.vm.network "forwarded_port", guest: 8080, host: 2212
		web.ssh.forward_agent = true       

	end

	# DataBase
	config.vm.define "db" do |db|   
		db.vm.hostname = "db"    
		db.vm.network "private_network", ip: "10.11.1.201", virtualbox__intnet: true
		db.vm.provider "virtualbox" do |v| 
			v.memory = 1024 
		end 

		db.vm.network "forwarded_port", guest: 22, host: 2221, id: 'ssh', auto_correct: true
		db.vm.network "forwarded_port", guest: 5432, host: 2222
		db.ssh.forward_agent = true 

	end

	# Puppet e shell provisioning
	config.vm.provision :shell do |shell|
		shell.inline = "mkdir -p /etc/puppet/modules;
    									puppet module install puppetlabs/apt
                      puppet module install puppetlabs-postgresql"
    end

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "puppet/manifests"
		puppet.manifest_file = "site.pp"
		puppet.module_path = "puppet/modules"
	end

end